#!/bin/sh

export BUILD_DIR="${BUILD_DIR:-./build}"

export RUST_INSTALL="${RUST_INSTALL:-1}"
export RUST_VERSION="${RUST_VERSION:-nightly}"

export NODEJS_INSTALL="${NODEJS_INSTALL:-1}"
export NODEJS_VERSION="${NODEJS_VERSION:-lts}"

export PYTHON_INSTALL="${PYTHON_INSTALL:-1}"
export PYTHON_VERSION="${PYTHON_VERSION:-3.10}"

export POSTGRESQL_INSTALL="${POSTGRESQL_INSTALL:-1}"
export POSTGRESQL_VERSION="${POSTGRESQL_VERSION:-17}"
export POSTGRESQL_DAEMON="${POSTGRESQL_DAEMON:-1}"

export VALKEY_INSTALL="${VALKEY_INSTALL:-1}"
export VALKEY_VERSION="${VALKEY_VERSION:-unstable}"
export VALKEY_DAEMON="${VALKEY_DAEMON:-1}"

export NGINX_INSTALL="${NGINX_INSTALL:-1}"
export NGINX_VERSION="${NGINX_VERSION:-mainline}"
export NGINX_DAEMOM="${NGINX_DAEMOM:-1}"

export CELERY_INSTALL="${CELERY_INSTALL:-1}"
export CELERY_DAEMOM="${CELERY_DAEMOM:-1}"

export WWWROOT_INSTALL="${WWWROOT_INSTALL:-1}"

export FACESWAPPER_INSTALL="${FACESWAPPER_INSTALL:-1}"
export FACESWAPPER_VENV="${FACESWAPPER_VENV:-/opt/venvs/swap-${PYTHON_VERSION}}"
