#!/bin/sh

export RUST_INSTALL=0
export NODEJS_INSTALL=0
export PYTHON_INSTALL=0
export POSTGRESQL_INSTALL=0
export VALKEY_INSTALL=0
export NGINX_INSTALL=0
export CELERY_INSTALL=0
export FACESWAPPER_INSTALL=0
export JUPYTER_NOTEBOOK_INSTALL=0
